/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lnc' at '10/20/16 3:18 PM' with Gradle 2.13
 *
 * @author lnc, @date 10/20/16 3:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
